"""
Custom Transform Pipeline for VideoMAE Training

This module provides transform pipelines for video preprocessing, normalization,
and masking generation for EVEREST VideoMAE training.
"""

import torch
import torch.nn as nn
import numpy as np
from masking_generator import TubeMaskingGenerator, RandomMaskingGenerator
import random


class VideoNormalize(object):
    """
    Normalize video tensor using custom mean and standard deviation.
    
    Args:
        mean (list): Mean values for each channel [R, G, B]
        std (list): Standard deviation values for each channel [R, G, B]
    """
    
    def __init__(self, mean, std):
        self.mean = torch.tensor(mean).view(3, 1, 1, 1)  # [C, 1, 1, 1] for broadcasting
        self.std = torch.tensor(std).view(3, 1, 1, 1)
    
    def __call__(self, video):
        """
        Normalize video tensor.
        
        Args:
            video (torch.Tensor): Video tensor of shape [C, T, H, W]
            
        Returns:
            torch.Tensor: Normalized video tensor
        """
        
        return (video - self.mean) / self.std


class DataAugmentationForVideoMAE(object):
    """
    Data augmentation and masking pipeline for VideoMAE training.
    
    This class handles:
    - Video normalization with custom mean/std
    - Masking generation (random, tube, or motion-centric)
    - Integration with VideoMAE model's masking requirements
    
    Args:
        normalize_mean (list): Mean values for normalization [R, G, B]
        normalize_std (list): Standard deviation values for normalization [R, G, B]
        window_size (tuple): Window size for masking (frames, height_patches, width_patches)
        mask_type (str): Type of masking - 'random', 'tube', or 'motion-centric'
        mask_ratio (float): Ratio of patches to mask
        motion_centric_masking_ratio (float): Ratio for motion-centric masking (if applicable)
    """
    
    def __init__(
        self,
        normalize_mean=[0.117, 0.114, 0.113],
        normalize_std=[0.208, 0.204, 0.203],
        window_size=(8, 14, 14),  # (frames, height_patches, width_patches)
        mask_type='motion-centric',
        mask_ratio=0.9,
        motion_centric_masking_ratio=0.7
    ):
        self.normalize_mean = normalize_mean
        self.normalize_std = normalize_std
        self.window_size = window_size
        self.mask_type = mask_type
        self.mask_ratio = mask_ratio
        self.motion_centric_masking_ratio = motion_centric_masking_ratio
        
        # Initialize normalizer
        self.normalizer = VideoNormalize(normalize_mean, normalize_std)
        
        # Initialize masking generator based on mask type
        self.mcm = False  # Motion-centric masking flag
        if mask_type == 'tube':
            self.masked_position_generator = TubeMaskingGenerator(
                window_size, mask_ratio
            )
        elif mask_type == 'random':
            self.masked_position_generator = RandomMaskingGenerator(
                window_size, mask_ratio
            )
        elif mask_type == 'motion-centric':
            # Motion-centric masking is handled by the model itself
            self.mcm = True
            self.masked_position_generator = 'Motion-centric Masking'
        else:
            raise ValueError(f"Unknown mask_type: {mask_type}. Must be 'random', 'tube', or 'motion-centric'")
    
    def __call__(self, video):
        """
        Apply transforms to video.
        
        Args:
            video (torch.Tensor): Video tensor of shape [C, T, H, W]
            
        Returns:
            tuple: (normalized_video, mask) where:
                - normalized_video: Normalized video tensor [C, T, H, W]
                - mask: Mask tensor or None (for motion-centric, mask is generated by model)
        """
        
        if isinstance(video, dict):
            print(f'Warning! Calling DataAugmentationForVideoMAE with dict input.')
            video = video['video']
            num_frames = video.shape[0]
        
            # Check if video has enough frames
            if num_frames < self.frames_to_sample:
                # If video is too short, repeat the last frame
                padding_needed = self.frames_to_sample - num_frames
                last_frame = video[-1:].repeat(padding_needed, 1, 1, 1)
                video = torch.cat([video, last_frame], dim=0)
                num_frames = video.shape[0]
            
            # Randomly sample consecutive frames
            max_start = num_frames - self.frames_to_sample
            if max_start < 0:
                start_frame = 0
            else:
                start_frame = random.randint(0, max_start)
            
            # Extract consecutive frames
            sampled_frames = video[start_frame:start_frame + self.frames_to_sample]
            
            # Temporal downsampling with stride
            downsampled_frames = sampled_frames[::self.temporal_stride]
            
            # Convert from [T, H, W, C] to [C, T, H, W]
            video = downsampled_frames.permute(3, 0, 1, 2).float()
            
            # Normalize to [0, 1] if not already (read_video returns uint8 [0, 255])
            max_val = video.max().item() if video.numel() > 0 else 0.0
            if max_val > 1.0:
                video = video / 255.0
        


        # Normalize video
        normalized_video = self.normalizer(video)
        
        # Generate mask if not motion-centric
        if self.mcm:
            # Motion-centric masking is handled by the model
            # Return 0 as placeholder (model will generate mask internally)
            return normalized_video, 0
        else:
            # Generate mask using the masking generator
            mask = self.masked_position_generator()
            # Convert numpy array to torch tensor
            mask = torch.from_numpy(mask).bool()
            return normalized_video, mask
    
    def __repr__(self):
        """String representation of the transform."""
        repr_str = "DataAugmentationForVideoMAE(\n"
        repr_str += f"  normalize_mean={self.normalize_mean},\n"
        repr_str += f"  normalize_std={self.normalize_std},\n"
        repr_str += f"  window_size={self.window_size},\n"
        repr_str += f"  mask_type={self.mask_type},\n"
        repr_str += f"  mask_ratio={self.mask_ratio},\n"
        if self.mcm:
            repr_str += f"  motion_centric_masking_ratio={self.motion_centric_masking_ratio}\n"
        repr_str += ")"
        return repr_str

